spring:
  datasource:
    url: jdbc:mysql://121.196.192.247:888//yi_db?serverTimezone=GMT%2B8
    username: root
    password: hala1207
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
